Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - main
     paths:
-      - 'lambda//lambda_function.py'
+      - 'lambda/**/lambda_function.py'  # Updated path
 
 jobs:
   deploy:
@@ -35,8 +35,14 @@ jobs:
 
       - name: Zip Lambda Function
         run: |
-          cd lambda/${{ matrix.function }}
-          zip -r ../../${{ matrix.function }}.zip .
+          if [ -d "lambda/${{ matrix.function }}" ]; then
+            cd lambda/${{ matrix.function }}
+            zip -r ../../${{ matrix.function }}.zip .
+            cd ../..
+          else
+            echo "Error: lambda/${{ matrix.function }} not found!"
+            exit 1
+          fi
 
       - name: Deploy to AWS Lambda
         uses: appleboy/lambda-action@master
